### ISSUE TITLE
Error if samples don't contain overlapping mutation

### ISSUE THREAD

**Issue by willemdek11** [Roth-Lab/pyclone-vi#14]
I kept running into errors while running:

`pyclone-vi fit -i pyclone_test.tsv -o merge_pyclone.h5 -c 40 -d beta-binomial -r 10`

After debugging for a while, I noticed it gives an error when there are 0 overlapping mutations in ALL samples.

Increasing the sample size makes it therefore impossible to get an output.

```
Traceback (most recent call last):
  File "/data/users/willem/miniconda3/envs/pyclonevi/bin/pyclone-vi", line 10, in <module>
    sys.exit(main())
  File "/data/users/willem/miniconda3/envs/pyclonevi/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/data/users/willem/miniconda3/envs/pyclonevi/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/data/users/willem/miniconda3/envs/pyclonevi/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/data/users/willem/miniconda3/envs/pyclonevi/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/users/willem/miniconda3/envs/pyclonevi/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/data/users/willem/miniconda3/envs/pyclonevi/lib/python3.8/site-packages/pyclone_vi/cli.py", line 113, in fit
    pyclone_vi.run.fit(**kwargs)
  File "/data/users/willem/miniconda3/envs/pyclonevi/lib/python3.8/site-packages/pyclone_vi/run.py", line 29, in fit
    log_p_data, mutations, samples = load_data(in_file, density, num_grid_points, precision=precision)
  File "/data/users/willem/miniconda3/envs/pyclonevi/lib/python3.8/site-packages/pyclone_vi/data.py", line 27, in load_data
    return np.stack(log_p_data), mutations, samples
  File "<__array_function__ internals>", line 5, in stack
  File "/data/users/willem/miniconda3/envs/pyclonevi/lib/python3.8/site-packages/numpy/core/shape_base.py", line 425, in stack
    raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack
```

**Comment by aroth85** [comment]
There needs to be overlapping mutations between samples. Are these related samples i.e. from the same patient?

A common mistake is to not include counts for positions that were not called as a variant in other samples. For each sample you should include counts for the union set of all mutations across all the samples. You may have to force your variant caller to output these and/or write a short script to pull the counts.

**Comment by willemdek11** [comment]
These samples are from different patients. The variants are germline filtered though. Would it help to include these variants as well?

**Comment by aroth85** [comment]
The samples need to be from the same patient, otherwise there is no evolutionary relationship between them. If they are from different patients you can just run them individually through PyClone-VI.

**Comment by willemdek11** [comment]
Thank you!
