### ISSUE TITLE
A Type Error while running pyclone-vi fit

### ISSUE THREAD

**Issue by dsagar18** [Roth-Lab/pyclone-vi#21]
I am trying to run pyclone-vi with my input file for 109 samples.
when I run the following command:
`pyclone-vi fit -i pyCloneTest.tsv -o pyCloneTest.out -c 40 -d beta-binomial -r 10`
I get the following error:
Traceback (most recent call last):
  File "/home/internal/NGS/group_vibha01/anaconda3/envs/pyclone-vi/bin/pyclone-vi", line 8, in <module>
    sys.exit(main())
  File "/home/internal/NGS/group_vibha01/anaconda3/envs/pyclone-vi/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/internal/NGS/group_vibha01/anaconda3/envs/pyclone-vi/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/internal/NGS/group_vibha01/anaconda3/envs/pyclone-vi/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/internal/NGS/group_vibha01/anaconda3/envs/pyclone-vi/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/internal/NGS/group_vibha01/anaconda3/envs/pyclone-vi/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/internal/NGS/group_vibha01/anaconda3/envs/pyclone-vi/lib/python3.10/site-packages/pyclone_vi/cli.py", line 113, in fit
    pyclone_vi.run.fit(**kwargs)
  File "/home/internal/NGS/group_vibha01/anaconda3/envs/pyclone-vi/lib/python3.10/site-packages/pyclone_vi/run.py", line 29, in fit
    log_p_data, mutations, samples = load_data(in_file, density, num_grid_points, precision=precision)
  File "/home/internal/NGS/group_vibha01/anaconda3/envs/pyclone-vi/lib/python3.10/site-packages/pyclone_vi/data.py", line 11, in load_data
    data, mutations, samples = load_pyclone_data(file_name)
  File "/home/internal/NGS/group_vibha01/anaconda3/envs/pyclone-vi/lib/python3.10/site-packages/pyclone_vi/data.py", line 31, in load_pyclone_data
    df = df[df['major_cn'] > 0]
  File "/home/internal/NGS/group_vibha01/anaconda3/envs/pyclone-vi/lib/python3.10/site-packages/pandas/core/ops/common.py", line 70, in new_method
    return method(self, other)
  File "/home/internal/NGS/group_vibha01/anaconda3/envs/pyclone-vi/lib/python3.10/site-packages/pandas/core/arraylike.py", line 56, in __gt__
    return self._cmp_method(other, operator.gt)
  File "/home/internal/NGS/group_vibha01/anaconda3/envs/pyclone-vi/lib/python3.10/site-packages/pandas/core/series.py", line 5623, in _cmp_method
    res_values = ops.comparison_op(lvalues, rvalues, op)
  File "/home/internal/NGS/group_vibha01/anaconda3/envs/pyclone-vi/lib/python3.10/site-packages/pandas/core/ops/array_ops.py", line 283, in comparison_op
    res_values = comp_method_OBJECT_ARRAY(op, lvalues, rvalues)
  File "/home/internal/NGS/group_vibha01/anaconda3/envs/pyclone-vi/lib/python3.10/site-packages/pandas/core/ops/array_ops.py", line 73, in comp_method_OBJECT_ARRAY
    result = libops.scalar_compare(x.ravel(), y, op)
  File "pandas/_libs/ops.pyx", line 107, in pandas._libs.ops.scalar_compare
TypeError: '>' not supported between instances of 'str' and 'int'
I am attaching the file with the issue. Can you please help me? Thank you!

**Comment by dsagar18** [comment]
I figured it out! 
Sorry to bother you, It was a stupid mistake.
Thank you anyway.
