### ISSUE TITLE
Data loading issue

### ISSUE THREAD

**Issue by mda-hillmanlab** [Roth-Lab/pyclone-vi#22]
When running pyclone-vi for the first time, I created a dataset based on the usage instructions (see attached file: 
[pyclone_test.txt](https://github.com/Roth-Lab/pyclone-vi/files/8646254/pyclone_test.txt)). I then run the following command, adapted from the vigenette:
pyclone-vi fit -i pyclone_test.txt -o pyclone_test.h5 -c 40 -d beta-binomial -r 10

This produces the following output and errors. As far as I can tell, my data are formatted identically to the example file "tracerx.tsv", and things run fine when I use that file as input.

Removing 3 mutations with major copy number zero

Traceback (most recent call last):
  File "/rsrch3/home/gyn_onc_rep_med/rthillman/.conda/envs/pyclone-vi/bin/pyclone-vi", line 8, in <module>
    sys.exit(main())
  File "/rsrch3/home/gyn_onc_rep_med/rthillman/.conda/envs/pyclone-vi/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/rsrch3/home/gyn_onc_rep_med/rthillman/.conda/envs/pyclone-vi/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/rsrch3/home/gyn_onc_rep_med/rthillman/.conda/envs/pyclone-vi/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/rsrch3/home/gyn_onc_rep_med/rthillman/.conda/envs/pyclone-vi/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/rsrch3/home/gyn_onc_rep_med/rthillman/.conda/envs/pyclone-vi/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/rsrch3/home/gyn_onc_rep_med/rthillman/.conda/envs/pyclone-vi/lib/python3.10/site-packages/pyclone_vi/cli.py", line 113, in fit
    pyclone_vi.run.fit(**kwargs)
  File "/rsrch3/home/gyn_onc_rep_med/rthillman/.conda/envs/pyclone-vi/lib/python3.10/site-packages/pyclone_vi/run.py", line 29, in fit
    log_p_data, mutations, samples = load_data(in_file, density, num_grid_points, precision=precision)
  File "/rsrch3/home/gyn_onc_rep_med/rthillman/.conda/envs/pyclone-vi/lib/python3.10/site-packages/pyclone_vi/data.py", line 11, in load_data
    data, mutations, samples = load_pyclone_data(file_name)
  File "/rsrch3/home/gyn_onc_rep_med/rthillman/.conda/envs/pyclone-vi/lib/python3.10/site-packages/pyclone_vi/data.py", line 78, in load_pyclone_data
    cn, mu, log_pi = cn_priors[(
TypeError: unhashable type: 'Series'

**Comment by jbedo** [comment]
I encountered this, was due to multiple mutant ids as pointed out in #12.

**Comment by edceeyuchen** [comment]
> I encountered this, was due to multiple mutant ids as pointed out in #12.

@jbedo ，Hello, jebdo, I met this problem, but I don't understand #12 answers? It's the problem about mutation_id col?

**Comment by jbedo** [comment]
Sorry this was a while ago so I don't quite remember, it might be that I
encountered this error when mutation_id and sample_id didn't form a
candidate key.
