### ISSUE TITLE
AttributeError: module 'numba' has no attribute 'jitclass'

### ISSUE THREAD

**Issue by jchenpku** [Roth-Lab/pyclone-vi#7]
$pyclone-vi --help
Traceback (most recent call last):
  File "/miniconda3/envs/pyclone-vi/bin/pyclone-vi", line 5, in <module>
    from pyclone_vi.cli import main
  File "/miniconda3/envs/pyclone-vi/lib/python3.8/site-packages/pyclone_vi/cli.py", line 3, in <module>
    import pyclone_vi.run
  File "/miniconda3/envs/pyclone-vi/lib/python3.8/site-packages/pyclone_vi/run.py", line 4, in <module>
    from pyclone_vi.data import load_data
  File "/miniconda3/envs/pyclone-vi/lib/python3.8/site-packages/pyclone_vi/data.py", line 172, in <module>
    @numba.jitclass([
AttributeError: module 'numba' has no attribute 'jitclass'

**Comment by aroth85** [comment]
Apologies. Numba has moved the jitclass to a different package. If you install an older version of numba through conda it should work. I will try to patch pyclone-vi in the next few days to work with the updated version.

**Comment by aroth85** [comment]
Should be fixed in f498d09fcd76fc8c3c7a18375b8f8b82cfd70ae4. Let me know if there is any issue.

**Comment by jchenpku** [comment]
Now the error disappeared. Thanks.
